### ISSUE TITLE
Doesn't list the personal repo (like ziadOUA / ziadOUA)

### ISSUE THREAD

**Issue by ziadOUA** [HiDe-Techno-Tips/GitHub-List-Repositories-HTML#1]
Hello

The program doesn't seem to fetch the personal repository (the one that contains the profile README)

Thanks.

**Comment by HimDek** [comment]
This is intended for use in public sites and will not show private repositories

**Comment by ziadOUA** [comment]
I didn't mention private repos (I know that those would need higher permissions regarding the API).

"Personal" repos are the one that contain the profile README (eg. : ziadOUA/ziadOUA)

**Comment by HimDek** [comment]
I decided to not include those because they are not software repos. Anyway, if you want those to display I will try to include a option soon.

**Comment by HimDek** [comment]
Fixed by https://github.com/HimDek/GitHub-List-Repositories-HTML/commit/feafbd179c6b22808375128b1464cc3afe19b6da
